DROP TABLE IF EXISTS users, items, booking, comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY                          NOT NULL PRIMARY KEY,
    name  VARCHAR(255)                                                     NOT NULL,
    email VARCHAR(512) UNIQUE CHECK (email != '' AND email ~ '^.+@.+\..+') NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    owner_id    BIGINT                                  NOT NULL REFERENCES users (id),
    available   VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time   TIMESTAMP WITHOUT TIME ZONE,
    status     varchar(255)                            NOT NULL,
    booker_id  BIGINT                                  NOT NULL REFERENCES users (id),
    item_id    BIGINT                                  NOT NULL REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    text      VARCHAR(512)                            NOT NULL,
    author_id BIGINT                                  NOT NULL REFERENCES users (id),
    item_id   BIGINT                                  NOT NULL REFERENCES items (id),
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);