DROP TABLE IF EXISTS users, items, booking CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512) UNIQUE                     NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    owner_id    INT                                     not null references users (id),
    available   VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_time DATE                                    NOT NULL,
    end_time   DATE                                    NOT NULL,
    status     varchar(255)                            NOT NULL,
    booker_id  INT                                     NOT NULL REFERENCES users (id),
    item_id    INT                                     NOT NULL REFERENCES items (id)
);